### ISSUE TITLE
Speakers don't turn on during calls

### ISSUE THREAD

**Issue by asmstudent** [MartinX3-AndroidDevelopment-LineageOS/bug_tracker#10]
**Platform:** TAMA
**Device:** AKARI, APOLLO, AKATSUKI
**Kernel version:** 4.14
**Android version:** 10.0

**Description**
Speakers don't turn on during calls

**Symptoms**
Sounds comes out only from earpiece even when speakers are turned on during calls

**How to reproduce**
Using speakers during calls

**Additional context**
Add any other context, e.g. upload logs or screenshots about the bug here.

[speaker.txt](https://github.com/MartinX3-AndroidDevelopment-LineageOS/bug_tracker/files/4210556/speaker.txt)

**Comment by MartinX3** [comment]
@asmstudent What was the behaviour on 9.0 and stock?

**Comment by asmstudent** [comment]
It was working on aosp 9 and I'm locked out of stock because frp lock ( second hand buyer)

**Comment by MartinX3** [comment]
Thank you

Redirected to https://github.com/sonyxperiadev/bug_tracker/issues/549
