### ISSUE TITLE
[Bug] Battery levels are wrong

### ISSUE THREAD

**Issue by MartinX3** [MartinX3-AndroidDevelopment-LineageOS/bug_tracker#2]
**Platform:** TAMA
**Device:** AKARI, APOLLO
**Kernel version:** 4.14
**Android version:** 10.0

**Description**
The battery levels are wrong

**Symptoms**
The system show wrong battery levels

**How to reproduce**
Charge & use the device

**Additional context**
[battery_dmesg.log](https://github.com/MartinX3-AndroidDevelopment-LineageOS/bug_tracker/files/4152422/battery_dmesg.log)
[battery_logcat.log](https://github.com/MartinX3-AndroidDevelopment-LineageOS/bug_tracker/files/4152423/battery_logcat.log)

Maybe the health service?
Maybe because LineageOS extended hardware interfaces?

**Comment by MartinX3** [comment]
From @nikdib 
**Platform:** TAMA
**Device:** AKARI, APOLLO, AKATSUKI (xz2c h8314)
**Kernel version:** 4.14
**Android version:** 10.0

**Description**
while using the phone the battery went down to 33% but then it never went down and I restarted 2 times. So I attached the charger and in 1 minute it went from 33% to 41 and it kept going up fast. but now there seems to be no bug momentarily... i will check



**Symptoms**
Write the symptoms here.

**How to reproduce**
I can't reproduce

**Additional context**
i have a screenshot but it doesn't help. in the circled part it was always charging and you can see that the battery even went down.
![Screenshot_20200204-110151_Impostazioni](https://user-images.githubusercontent.com/60649691/73739308-3faff380-4746-11ea-86f0-67e8c6a3c167.png)

**Comment by nikdib** [comment]
i think that this problem appears below the 50% of battery because for the second times i had this problem but now at 42%. I think also the phone can't always go in deep sleep.
I make a video when i put the phone in charging from 42% and in 2 minutes it's arrived to 50% so too fast but i have the original 7.5 watt charger and it can't be fast charging. If you want the video tell me because i can't upload here.

**Comment by MartinX3** [comment]
@nikdib Thank you, I don't need the video
But if you have a logcat and dmesg for me, it would be nice, too :)

**Comment by MartinX3** [comment]
Seems like the battery level is everytime wrong.
I lost 30% battery at night in plane mode.
I doubt a battery drain.

**Comment by MartinX3** [comment]
According to the treble specification a workaround for the bugs should be flashing my provided Sony AOSP vendor.img from the other XDA thread.

**Comment by MartinX3** [comment]
Looking into the Pixel Experience repositories to look for a fix.

**Comment by MartinX3** [comment]
Should be fixed in the next update.

Please report again if it is still not fixed.

**Comment by MartinX3** [comment]
Still open.
Jumped from ~73% (charged in SonyAOSP) back to 99% (In LienageOS).

**Comment by MartinX3** [comment]
Ahh, appears on Sony AOSP, too.
Delegated to https://github.com/sonyxperiadev/bug_tracker/issues/539
