### ISSUE TITLE
[Bug] Wifi and mobile are unstable

### ISSUE THREAD

**Issue by MartinX3** [MartinX3-AndroidDevelopment-LineageOS/bug_tracker#3]
**Platform:** TAMA
**Device:** AKARI, APOLLO
**Kernel version:** 4.14
**Android version:** 10.0

**Description**
The Wifi and mobile are unstable

**Symptoms**
The Wifi and mobile are unstable

**How to reproduce**
Use the device

**Additional context**
[battery_dmesg.log](https://github.com/MartinX3-AndroidDevelopment-LineageOS/bug_tracker/files/4152422/battery_dmesg.log)
[battery_logcat.log](https://github.com/MartinX3-AndroidDevelopment-LineageOS/bug_tracker/files/4152423/battery_logcat.log)

Maybe because of transpower?
Hardware interfaces extended by LineageOS?

**Comment by MartinX3** [comment]
From @nikdib 
**Platform:** TAMA
**Device:** AKARI, APOLLO, AKATSUKI (xz2c h8314)
**Kernel version:** 4.14
**Android version:** 10.0

**Description**
randomly the wifi disconnects and reconnects after maybe 1 minutes

**Symptoms**
it's random

**How to reproduce**
i can't reproduce it but just wait

**Additional context**
i take a log with an app (alogcat root) while the bug was happening. I don't know if it's helpful for you.
[alogcat.2020-02-04-11-36-51+0100.txt](https://github.com/MartinX3-AndroidDevelopment-LineageOS/bug_tracker/files/4152782/alogcat.2020-02-04-11-36-51%2B0100.txt)

**Comment by nikdib** [comment]
I have to report that now i flashed stock sony android 10 fw (switzerland fw) because i need camera and i have this issue of wifi unstable but less frequently. Maybe it could be a bug of android 10 or sony's modem and not of this particular rom.

**Comment by MartinX3** [comment]
> I have to report that now i flashed stock sony android 10 fw (switzerland fw) because i need camera and i have this issue of wifi unstable but less frequently. Maybe it could be a bug of android 10 or sony's modem and not of this particular rom.

That's weird.
A family member has a locked XZ2 Single Sim with Switzerland 10.0 Firmware and say there are no wifi problems with device.
Maybe coincidence. :S

**Comment by nikdib** [comment]
i don't know why but on stock italy pie fw (my country) i haven't any problem with wifi so i don't think that my phone has an hardware problem.

**Comment by MartinX3** [comment]
I'm glad to hear, that your device is fine.

And luckily my port won't do any damage, since hardware specific limits/ranges are specified in the well tested SODP kernel.

**Comment by MartinX3** [comment]
According to the treble specification a workaround for the bugs should be flashing my provided Sony AOSP vendor.img from the other XDA thread.

**Comment by MartinX3** [comment]
Looking into the Pixel Experience repositories to look for a fix.

**Comment by MartinX3** [comment]
Should be now in line with SODP with my next update.

**Comment by MartinX3** [comment]
Ahh, appears on Sony AOSP and in the sony stock firmware, too.
Delegated to https://github.com/sonyxperiadev/bug_tracker/issues/540
